Repository Elaech/A7-IP, pull requests merged in 2020-04, with the labels that each got.

#2 Front end create domain
  Final Project/Client/fiimentor/main/Context.js
  Final Project/Client/fiimentor/main/core/domain/Class1.js
  Final Project/Client/fiimentor/main/core/domain/Mesaj.js
  Final Project/Client/fiimentor/main/core/domain/Profesor.js
  Final Project/Client/fiimentor/main/core/domain/Student.js
  Final Project/Client/fiimentor/main/core/domain/Tutore.js
  Final Project/Client/fiimentor/main/core/domain/User.js
  Final Project/Client/fiimentor/main/core/services/AlertService.js
  Final Project/Client/fiimentor/main/core/services/ApiService.js
  Final Project/Client/fiimentor/main/core/services/ServicesInterface1.js
  Final Project/Client/fiimentor/main/services/AxiosService.js
  Final Project/Client/fiimentor/main/services/HttpApiService.js
  Final Project/Client/fiimentor/main/services/ServiceImplementation1.js
  Final Project/Client/fiimentor/next.config.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/yarn.lock
Labels: Please Review

#5 Hotfix frontend resolve flow type
  Final Project/Client/fiimentor/.babelrc
  Final Project/Client/fiimentor/.env.dev
  Final Project/Client/fiimentor/.flowconfig
  Final Project/Client/fiimentor/next.config.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/yarn.lock
Labels: Please Review

#9 Login form
  Final Project/Client/fiimentor/main/components/Generics/EmailInput.jsx
  Final Project/Client/fiimentor/main/components/Generics/PasswordInput.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginForm.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginFormStyles.jsx
  Final Project/Client/fiimentor/main/globalStyledVariables.jsx
  Final Project/Client/fiimentor/next.config.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-Bold.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-BoldItalic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-ExtraBold.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-ExtraBoldItalic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-ExtraLight.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-ExtraLightItalic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-Italic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-Light.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-LightItalic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-Medium.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-MediumItalic.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-Regular.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-SemiBold.ttf
  Final Project/Client/fiimentor/static/fonts/Spectral/Spectral-SemiBoldItalic.ttf
  Final Project/Client/fiimentor/yarn.lock
Labels: Please Review

#10 Forgot passwrod
  Final Project/Client/fiimentor/main/components/ForgotPasswordComponent/ForgotPasswordForm.jsx
  Final Project/Client/fiimentor/main/components/ForgotPasswordComponent/ForgotPasswordFormStyles.jsx
  Final Project/Client/fiimentor/main/components/Generics/CheckBox.jsx
  Final Project/Client/fiimentor/main/components/Generics/TextAreaInput.jsx
  Final Project/Client/fiimentor/pages/index.jsx
Labels: Please Review

#12 Register form
  Final Project/Client/fiimentor/main/components/Generics/TextInput.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginFormStyles.jsx
  Final Project/Client/fiimentor/main/components/RegisterFormComponents/RegisterForm.jsx
  Final Project/Client/fiimentor/main/components/RegisterFormComponents/RegisterFormStyles.jsx
Labels: Please Review

#17 Login form layout
  Final Project/Client/fiimentor/main/components/ForgotPasswordComponent/ForgotPasswordForm.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginForm.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginFormStyles.jsx
  Final Project/Client/fiimentor/main/components/LoginPageLayout/LoginPageLayout.css
  Final Project/Client/fiimentor/main/components/LoginPageLayout/LoginPageLayout.jsx
  Final Project/Client/fiimentor/main/globalStyledVariables.jsx
  Final Project/Client/fiimentor/next.config.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/pages/_app.jsx
  Final Project/Client/fiimentor/pages/index.jsx
  Final Project/Client/fiimentor/public/final-logo.png
  Final Project/Client/fiimentor/static/images/final-logo.png
  Final Project/Client/fiimentor/yarn.lock
Labels: Please Review

#18 Fixed Login: replace email with username
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginForm.jsx
Labels: HOTFIX, Please Review

#21 Integrate Front End with Back end
  Final Project/Client/fiimentor/.dev.env
  Final Project/Client/fiimentor/.env.dev
  Final Project/Client/fiimentor/main/components/Componenta1.jsx
  Final Project/Client/fiimentor/main/components/Generics/Modal/Modal.css
  Final Project/Client/fiimentor/main/components/Generics/Modal/Modal.jsx
  Final Project/Client/fiimentor/main/components/LoginFormComponents/LoginForm.jsx
  Final Project/Client/fiimentor/main/components/LoginPageLayout/LoginPageLayout.css
  Final Project/Client/fiimentor/main/components/LoginPageLayout/LoginPageLayout.jsx
  Final Project/Client/fiimentor/main/components/RegisterFormComponents/RegisterForm.jsx
  Final Project/Client/fiimentor/main/components/RegisterFormComponents/RegisterFormStyles.jsx
  Final Project/Client/fiimentor/main/core/domain/Profesor.js
  Final Project/Client/fiimentor/main/core/domain/Tutore.js
  Final Project/Client/fiimentor/main/core/domain/User.js
  Final Project/Client/fiimentor/main/core/services/ApiService.js
  Final Project/Client/fiimentor/main/services/AxiosService.js
  Final Project/Client/fiimentor/main/services/HttpApiService.js
  Final Project/Client/fiimentor/main/store/AppState.js
  Final Project/Client/fiimentor/main/store/User/loginUserThunk.js
  Final Project/Client/fiimentor/main/store/User/registerUserThunk.js
  Final Project/Client/fiimentor/main/store/User/setUserTokenThunk.js
  Final Project/Client/fiimentor/main/store/User/tokenReducer.js
  Final Project/Client/fiimentor/main/store/User/userActions.js
  Final Project/Client/fiimentor/main/store/store.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/pages/_app.jsx
  Final Project/Client/fiimentor/pages/index.jsx
  Final Project/Client/fiimentor/tests/store/User/loginUserThunk.test.js
  Final Project/Client/fiimentor/tests/store/User/setUserTokenThunk.test.js
  Final Project/Client/fiimentor/tests/store/User/tokenReducer.test.js
  Final Project/Client/fiimentor/yarn.lock
  Final Project/Server/fiimentor/controllers/authController.ts
  Final Project/Server/fiimentor/index.ts
  Final Project/Server/fiimentor/ormconfig.json
Labels: Please Review

#35 creating-PostPageBadge
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostPageBadge.jsx
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostPageStyle.jsx
  Final Project/Client/fiimentor/main/core/services/ApiService.js
  Final Project/Client/fiimentor/main/services/HttpApiService.js
  Final Project/Client/fiimentor/pages/index.jsx
Labels: Approved

#34 Post form
  Final Project/Client/fiimentor/main/components/Generics/CheckBox.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostForm.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostFormStyles.jsx
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/pages/index.jsx
  Final Project/Client/fiimentor/yarn.lock
Labels: Please Review

#33 Posts Thunk
  Final Project/Client/fiimentor/main/store/Post/createAPostThunk.js
  Final Project/Client/fiimentor/main/store/Post/postActions.js
Labels: Please Review

#36 Integrate message functionality
  .gitignore
  Final Project/Client/fiimentor/main/WithReduxStore.jsx
  Final Project/Client/fiimentor/main/components/Generics/CheckBox.jsx
  Final Project/Client/fiimentor/main/components/Generics/Select/Select.jsx
  Final Project/Client/fiimentor/main/components/Generics/Select/SelectOption.jsx
  Final Project/Client/fiimentor/main/components/Generics/TextAreaInput.jsx
  Final Project/Client/fiimentor/main/components/Generics/TextInput.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostForm.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostFormStyles.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/SelectOptions.js
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostPageBadge.jsx
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostPageStyle.jsx
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostsPage.jsx
  Final Project/Client/fiimentor/main/core/domain/Profesor.js
  Final Project/Client/fiimentor/main/core/services/ApiService.js
  Final Project/Client/fiimentor/main/services/HttpApiService.js
  Final Project/Client/fiimentor/main/store/AppState.js
  Final Project/Client/fiimentor/main/store/Post/createAPostThunk.js
  Final Project/Client/fiimentor/main/store/Profesor/getProfesoriThunk.js
  Final Project/Client/fiimentor/main/store/Profesor/profesorActions.js
  Final Project/Client/fiimentor/main/store/Profesor/profesorReducer.js
  Final Project/Client/fiimentor/main/store/User/loginUserThunk.js
  Final Project/Client/fiimentor/main/store/User/registerUserThunk.js
  Final Project/Client/fiimentor/main/store/User/setUserTokenThunk.js
  Final Project/Client/fiimentor/main/store/User/tokenReducer.js
  Final Project/Client/fiimentor/main/store/store.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/pages/_app.jsx
  Final Project/Client/fiimentor/pages/homepage/post.jsx
  Final Project/Client/fiimentor/pages/index.jsx
  Final Project/Client/fiimentor/yarn.lock
  Final Project/Server/fiimentor/ormconfig.json
  Final Project/Server/fiimentor/package-lock.json
Labels: Please Review

#37 Post functionality added
  .gitignore
  Final Project/Client/fiimentor/main/WithReduxStore.jsx
  Final Project/Client/fiimentor/main/components/Generics/CheckBox.jsx
  Final Project/Client/fiimentor/main/components/Generics/Select/Select.jsx
  Final Project/Client/fiimentor/main/components/Generics/Select/SelectOption.jsx
  Final Project/Client/fiimentor/main/components/Generics/TextAreaInput.jsx
  Final Project/Client/fiimentor/main/components/Generics/TextInput.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostForm.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/PostFormStyles.jsx
  Final Project/Client/fiimentor/main/components/PostFormComponents/SelectOptions.js
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostPageStyle.jsx
  Final Project/Client/fiimentor/main/components/PostPageComponent/PostsPage.jsx
  Final Project/Client/fiimentor/main/core/domain/Mesaj.js
  Final Project/Client/fiimentor/main/core/domain/Postare.js
  Final Project/Client/fiimentor/main/core/domain/Profesor.js
  Final Project/Client/fiimentor/main/core/services/ApiService.js
  Final Project/Client/fiimentor/main/services/HttpApiService.js
  Final Project/Client/fiimentor/main/store/AppState.js
  Final Project/Client/fiimentor/main/store/Post/createAPostThunk.js
  Final Project/Client/fiimentor/main/store/Post/postActions.js
  Final Project/Client/fiimentor/main/store/Profesor/getProfesoriThunk.js
  Final Project/Client/fiimentor/main/store/Profesor/profesorActions.js
  Final Project/Client/fiimentor/main/store/Profesor/profesorReducer.js
  Final Project/Client/fiimentor/main/store/User/loginUserThunk.js
  Final Project/Client/fiimentor/main/store/User/registerUserThunk.js
  Final Project/Client/fiimentor/main/store/User/setUserTokenThunk.js
  Final Project/Client/fiimentor/main/store/User/tokenReducer.js
  Final Project/Client/fiimentor/main/store/store.js
  Final Project/Client/fiimentor/package.json
  Final Project/Client/fiimentor/pages/_app.jsx
  Final Project/Client/fiimentor/pages/homepage/post.jsx
  Final Project/Client/fiimentor/pages/index.jsx
  Final Project/Client/fiimentor/yarn.lock
  Final Project/Server/fiimentor/Repositories/GroupeMemberRepository.ts
  Final Project/Server/fiimentor/Repositories/GroupeRepository.ts
  Final Project/Server/fiimentor/Repositories/PostRepository.ts
  Final Project/Server/fiimentor/Repositories/PrivateMessageRepository.ts
  Final Project/Server/fiimentor/Repositories/UserRepository.ts
  Final Project/Server/fiimentor/controllers/authController.ts
  Final Project/Server/fiimentor/controllers/groupeController.ts
  Final Project/Server/fiimentor/controllers/index.ts
  Final Project/Server/fiimentor/controllers/postController.ts
  Final Project/Server/fiimentor/controllers/professorController.ts
  Final Project/Server/fiimentor/controllers/tutorGroupeController.ts
  Final Project/Server/fiimentor/index.ts
  Final Project/Server/fiimentor/models/entities/Groupe.ts
  Final Project/Server/fiimentor/package-lock.json
  Final Project/Server/fiimentor/package.json
  Final Project/Server/fiimentor/routes/groupe.ts
  Final Project/Server/fiimentor/routes/index.ts
  Final Project/Server/fiimentor/routes/post.ts
  Final Project/Server/fiimentor/routes/professor.ts
  Final Project/Server/fiimentor/utils/automatedScripts/allProfessorsGroup.ts
  Final Project/Server/fiimentor/utils/automatedScripts/allStudentGroups.ts
  Final Project/Server/fiimentor/utils/automatedScripts/allUsersGroup.ts
  Final Project/Server/fiimentor/utils/automatedScripts/generateGroups.ts
Labels: Please Review

#42 create create the details form after registration
  Final Project/Client/fiimentor/main/components/FormAfterRegistration/FormAfterRegistration.jsx
  Final Project/Client/fiimentor/main/components/FormAfterRegistration/FormAfterRegistrationStyles.jsx
  Final Project/Client/fiimentor/main/components/FormAfterRegistration/SelectOptionsForm.js
Labels: Please Review

#44 Create Search Thunk
  Final Project/Client/fiimentor/main/store/Search/SearchActions.js
  Final Project/Client/fiimentor/main/store/Search/createSearchThunk.js
Labels: Needs Work

#43 View posts
  Final Project/Client/fiimentor/main/components/ViewPostsComponent/ViewPosts.jsx
  Final Project/Client/fiimentor/main/components/ViewPostsComponent/ViewPostsStyle.jsx
  Final Project/Client/fiimentor/pages/homepage/post.jsx
Labels: Needs Work
